name: Deployment

on:
  workflow_call:
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      SSH_PASSPHRASE:
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH Key
        env:
          SSH_AUTH_SOCK: /tmp/ssh-auth.sock
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 0600 ~/.ssh/deploy_key
          ssh-keygen -p -P "${{ secrets.SSH_PASSPHRASE }}" -N "" -f ~/.ssh/deploy_key
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add ~/.ssh/deploy_key

      - uses: actions/checkout@v4
        name: Checkout

      - name: Set up PHP Version
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: andres-montanez/magallanes

      - name: Get Environment
        id: environment
        run: echo "target=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')" >> $GITHUB_OUTPUT

      - name: Deployment
        env:
          SSH_AUTH_SOCK: /tmp/ssh-auth.sock
        run: |
          mkdir -p ./.mage/logs
          composer global exec mage deploy ${{ steps.environment.outputs.target }}

      - name: Upload Logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: deployment
          path: .mage/logs
          retention-days: 7

      - name: Echo logs
        run: find .mage/logs/ -type f -exec cat {} +
        if: always()
