name: Manual Deployment

on:
  workflow_dispatch:

jobs:
  deployment:
    name: Deployment
    uses: ./.github/workflows/deployment.yml
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
